# Generated by Django 4.2 on 2024-05-10 19:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=156, verbose_name='Категория статьи')),
            ],
            options={
                'verbose_name': 'Категории (статьи)',
                'verbose_name_plural': 'Категории (статьи)',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=156, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Категории товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название характеристики')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_siteapp.categoryproduct', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Характеристика (товары)',
                'verbose_name_plural': 'Характеристики (товары)',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=156, verbose_name='Город/Регион')),
            ],
            options={
                'verbose_name': 'Города/Регионы',
                'verbose_name_plural': 'Города/Регионы',
            },
        ),
        migrations.CreateModel(
            name='ContentHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zagolovok', models.CharField(max_length=156, verbose_name='Заголовок контента')),
                ('text', models.TextField(verbose_name='Текст контента')),
                ('image', models.ImageField(upload_to='contenthome_images', verbose_name='Фото контента')),
            ],
            options={
                'verbose_name': 'Контент (Домашняя страница)',
                'verbose_name_plural': 'Контент (Домашняя страница)',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('new', models.BooleanField()),
                ('xit', models.BooleanField(verbose_name='Хит')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_siteapp.categoryproduct', verbose_name='Категория')),
                ('images', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Не проверен', 'Не проверен'), ('Удовлетворён', 'Удовлетворён'), ('Не удовлетворён', 'Не удовлетворён')], default='Не проверен', max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Оценка от 0,5 до 5 с шагом 0,5', max_digits=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('dost', models.TextField(verbose_name='Достоинства')),
                ('nedos', models.TextField(verbose_name='Недостатки')),
                ('obj', models.TextField(verbose_name='Общие впечатления')),
                ('image', models.ImageField(upload_to='review_images', verbose_name='Фотографии')),
                ('name', models.CharField(max_length=156, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата')),
                ('status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_siteapp.reviewstatus')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='backend_siteapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_siteapp.characteristic', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_siteapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Значение характеристики (товары)',
                'verbose_name_plural': 'Значения характеристик (товары)',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zagolovok', models.CharField(max_length=156, verbose_name='Заголовок статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('pod_zagolovok', models.CharField(max_length=156, verbose_name='Подзаголовок статьи')),
                ('image', models.ImageField(upload_to='article_image', verbose_name='Фото статьи')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_siteapp.categoryarticle', verbose_name='Категория')),
                ('tovar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_siteapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
