# Generated by Django 4.2 on 2024-05-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0004_heroslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSlide',
        ),
    ]
