# Generated by Django 4.2 on 2024-05-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0005_delete_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_images', verbose_name='Лого магазина')),
                ('name', models.CharField(max_length=156, verbose_name='Название магазина')),
                ('description', models.TextField(verbose_name='Описание магазина')),
            ],
        ),
    ]
