# Generated by Django 4.2 on 2024-05-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0007_image_heroslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSlider',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
