# Generated by Django 4.2 on 2024-05-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0008_delete_heroslider_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tovar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='backend_siteapp.product', verbose_name='Товар'),
        ),
    ]
