# Generated by Django 4.2 on 2024-05-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0011_product_articles_alter_article_tovar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='categoryhome_image', verbose_name='Изображение категории')),
            ],
        ),
        migrations.CreateModel(
            name='Nishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название низшей подкатегории')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Низшие подкатегории',
                'verbose_name_plural': 'Низшие подкатегории',
            },
        ),
        migrations.CreateModel(
            name='PodCategoryss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название подкатегории')),
                ('nish_category', models.ManyToManyField(to='backend_siteapp.nishe', verbose_name='Низшие подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегории Категорий',
                'verbose_name_plural': 'Подкатегории Категорий',
            },
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='characteristicvalue',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='characteristicvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='CharacteristicValue',
        ),
        migrations.AddField(
            model_name='categoryse',
            name='pod_category',
            field=models.ManyToManyField(to='backend_siteapp.podcategoryss', verbose_name='Подкатегория Категории'),
        ),
    ]
