# Generated by Django 4.2 on 2024-05-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0012_categoryse_nishe_podcategoryss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='backend_siteapp.nishe'),
        ),
    ]
