# Generated by Django 4.2 on 2024-05-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0013_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='backend_siteapp.nishe', verbose_name='Категория'),
        ),
    ]
