# Generated by Django 4.2 on 2024-05-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0015_contentcategory_alter_categoryse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'verbose_name': 'Контент (category.html)', 'verbose_name_plural': 'Контент (category.html)'},
        ),
    ]
