# Generated by Django 4.2 on 2024-05-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0016_alter_contentcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcategoryss',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pod_category_image', verbose_name='Фото подкатегории'),
        ),
    ]
