# Generated by Django 4.2 on 2024-05-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0017_podcategoryss_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название контента')),
                ('image', models.ImageField(upload_to='sub_category_content_image', verbose_name='Фото контента')),
                ('text', models.TextField(verbose_name='Текст контента')),
            ],
            options={
                'verbose_name': 'Контент (subcategory.html)',
                'verbose_name_plural': 'Контент (subcategory.html)',
            },
        ),
    ]
