# Generated by Django 4.2 on 2024-05-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0018_contentsub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название')),
                ('text', models.CharField(max_length=156, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Характеристики (товары)',
                'verbose_name_plural': 'Характеристики (товары)',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='xar',
            field=models.ManyToManyField(to='backend_siteapp.xar', verbose_name='Характеристики'),
        ),
    ]
