# Generated by Django 4.2 on 2024-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0020_alter_xar_options_product_sposob_paym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Умная характеристика',
                'verbose_name_plural': 'Умные характеристики',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='smart_characteristics',
            field=models.ManyToManyField(blank=True, to='backend_siteapp.smartcharacteristic', verbose_name='Умные характеристики'),
        ),
    ]
