# Generated by Django 4.2 on 2024-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0022_remove_smartcharacteristic_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcharacteristic',
            name='hex_code',
            field=models.CharField(default=1, max_length=7, verbose_name='Hex-код цвета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartcharacteristic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название цвета'),
        ),
    ]
