# Generated by Django 4.2 on 2024-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0023_smartcharacteristic_hex_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcharacteristic',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Hex-код цвета'),
        ),
        migrations.AlterField(
            model_name='smartcharacteristic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название цвета'),
        ),
    ]
