# Generated by Django 4.2 on 2024-05-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0024_alter_smartcharacteristic_hex_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcharacteristic',
            name='name_w',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='smartcharacteristic',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
