# Generated by Django 4.2 on 2024-05-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0025_smartcharacteristic_name_w_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcharacteristic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
