# Generated by Django 4.2 on 2024-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0026_alter_smartcharacteristic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='magaz',
            field=models.ManyToManyField(blank=True, null=True, to='backend_siteapp.magazin', verbose_name='Магазин'),
        ),
    ]
