# Generated by Django 4.2 on 2024-05-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0028_alter_product_magaz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazin',
            options={'verbose_name': 'Магазины', 'verbose_name_plural': 'Магазины'},
        ),
    ]
