# Generated by Django 4.2 on 2024-05-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0029_alter_magazin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='product', to='backend_siteapp.review'),
        ),
    ]
