# Generated by Django 4.2 on 2024-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0030_product_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Название')),
                ('value', models.CharField(max_length=156, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Фильтрация (Товары)',
                'verbose_name_plural': 'Фильтрация (Товары)',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='filter',
            field=models.ManyToManyField(blank=True, to='backend_siteapp.filterproduct', verbose_name='Фильтрация'),
        ),
    ]
