# Generated by Django 4.2 on 2024-06-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0032_alter_product_status_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status_product',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии'), ('on_order', 'Под заказ')], max_length=56),
        ),
    ]
