# Generated by Django 4.2 on 2024-06-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_siteapp', '0035_alter_product_status_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pod_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_siteapp.podcategoryss'),
        ),
    ]
